name: Go package
on:
  release:
    types: [created]

permissions:
    contents: write
    packages: write

jobs:
  releases-amd64:
    name: Release Go AMD64 Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        goos: [linux, darwin]
        # goarch: [arm64, arm]
        # goarm: [5, 6, 7]
        # exclude:
        #   - goarch: arm
        #     goos: "darwin"
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: ${{ matrix.goos }}
        goarch: amd64
        extra_files: LICENSE README.md
    
  releases-arm:
    name: Release Go ARM Binary
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # goos: [linux, darwin]
        goarch: [arm64, arm]
        goarm: [5, 6, 7]
        # exclude:
        #   - goarch: arm
        #     goos: "darwin"
    steps:
    - uses: actions/checkout@v3
    - uses: wangyoucao577/go-release-action@v1
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        goos: linux
        goarch: ${{ matrix.goarch }}
        goarm: ${{ matrix.goarm }}
        extra_files: LICENSE README.md
      